
import { Drug } from '../types';

// Mock data for testing
export const mockDrugs: Drug[] = [
  {
    id: "d1",
    name: "ZenRelief",
    manufacturer: "ZenPharma Inc.",
    batchNumber: "BATCH-1234",
    expiryDate: "2025-12-31",
    licenseNumber: "LIC-12345",
    sgtin: "sgtin:01234567890123.123456",
    ownerId: "user1",
    ownerName: "ZenPharma Inc.",
    ownerRole: "manufacturer",
    gtin: "01234567890123",
    manufacturerId: "user1",
    manufacturerName: "ZenPharma Inc.",
    productName: "ZenRelief",
    dosage: "10mg",
    status: "manufactured",
    currentOwnerId: "user1",
    currentOwnerName: "ZenPharma Inc.",
    currentOwnerRole: "manufacturer"
  },
  {
    id: "d2",
    name: "CardioZen",
    manufacturer: "ZenPharma Inc.",
    batchNumber: "BATCH-1235",
    expiryDate: "2026-01-15",
    licenseNumber: "LIC-12346",
    sgtin: "sgtin:01234567890124.123457",
    ownerId: "user2",
    ownerName: "MediDistribute LLC",
    ownerRole: "distributor",
    gtin: "01234567890124",
    manufacturerId: "user1",
    manufacturerName: "ZenPharma Inc.",
    productName: "CardioZen",
    dosage: "25mg",
    status: "shipped",
    currentOwnerId: "user2",
    currentOwnerName: "MediDistribute LLC",
    currentOwnerRole: "distributor"
  },
  {
    id: "d3",
    name: "PainEase",
    manufacturer: "ZenPharma Inc.",
    batchNumber: "BATCH-1236",
    expiryDate: "2025-06-30",
    licenseNumber: "LIC-12347",
    sgtin: "sgtin:01234567890125.123458",
    ownerId: "user3",
    ownerName: "ZenMed Pharmacy",
    ownerRole: "dispenser",
    gtin: "01234567890125",
    manufacturerId: "user1",
    manufacturerName: "ZenPharma Inc.",
    productName: "PainEase",
    dosage: "50mg",
    status: "received",
    currentOwnerId: "user3",
    currentOwnerName: "ZenMed Pharmacy",
    currentOwnerRole: "dispenser"
  },
  // A drug with an anomalous flow (skips distributor)
  {
    id: "d4",
    name: "AnomalyMed",
    manufacturer: "ZenPharma Inc.",
    batchNumber: "BATCH-1237",
    expiryDate: "2025-08-15",
    licenseNumber: "LIC-12348",
    sgtin: "sgtin:01234567890126.123459",
    ownerId: "user3",
    ownerName: "ZenMed Pharmacy",
    ownerRole: "dispenser",
    gtin: "01234567890126",
    manufacturerId: "user1",
    manufacturerName: "ZenPharma Inc.",
    productName: "AnomalyMed",
    dosage: "100mg",
    status: "dispensed",
    currentOwnerId: "user3",
    currentOwnerName: "ZenMed Pharmacy",
    currentOwnerRole: "dispenser"
  },
  // A drug with a gap in its timeline
  {
    id: "d5",
    name: "TimeGapMed",
    manufacturer: "ZenPharma Inc.",
    batchNumber: "BATCH-1238",
    expiryDate: "2025-10-20",
    licenseNumber: "LIC-12349",
    sgtin: "sgtin:01234567890127.123460",
    ownerId: "user2",
    ownerName: "MediDistribute LLC",
    ownerRole: "distributor",
    gtin: "01234567890127",
    manufacturerId: "user1",
    manufacturerName: "ZenPharma Inc.",
    productName: "TimeGapMed",
    dosage: "75mg",
    status: "in-transit",
    currentOwnerId: "user2",
    currentOwnerName: "MediDistribute LLC",
    currentOwnerRole: "distributor"
  }
];
