// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfqtonpajvkkugtiuxnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcXRvbnBhanZra3VndGl1eG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDAwNzgsImV4cCI6MjA1OTQ3NjA3OH0.5WgL6fTKUZo8lUqG3ygZTck0SIPBjCSg0NajnYeJNx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);